//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Id { get; set; }
        public int GuestsInRoomId { get; set; }
        public System.DateTime BillDate { get; set; }
        public byte NoOfDays { get; set; }
        public decimal RatePerDay { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal TotalBeforeTax { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public decimal TotalAfterTax { get; set; }
    
        public virtual GuestsInRoom GuestsInRoom { get; set; }
    }
}
