//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MotelDBEntities : DbContext
    {
        public MotelDBEntities()
            : base("name=MotelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<GuestsInRoom> GuestsInRooms { get; set; }
        public virtual DbSet<Parking> Parkings { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
    }
}
