//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestsInRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuestsInRoom()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int GuestsInRoomId { get; set; }
        public byte RoomId { get; set; }
        public int GuestId { get; set; }
        public bool isMainGuest { get; set; }
        public System.DateTime DateIn { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual Room Room { get; set; }
    }
}
